/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SCB_1.h"
#include "SCB_1_SPI_UART.h"
#include "SCB_1_PINS.h"
#include "SCB_1_SPI_UART_PVT.h"
#include "SCB_1_PVT.h"
#include "SCB_1_BOOT.h"
#include "SCB_2.h"
#include "SCB_2_I2C.h"
#include "SCB_2_PINS.h"
#include "SCB_2_I2C_PVT.h"
#include "SCB_2_PVT.h"
#include "SCB_2_BOOT.h"
#include "LED_SEG_PWM.h"
#include "Seg_1.h"
#include "Seg_1_aliases.h"
#include "Seg_2.h"
#include "Seg_2_aliases.h"
#include "Seg_3.h"
#include "Seg_3_aliases.h"
#include "Seg_4.h"
#include "Seg_4_aliases.h"
#include "Clock_1.h"
#include "PWM_Mux_Reg.h"
#include "Timer_Interrupt.h"
#include "NRF_CE.h"
#include "NRF_CE_aliases.h"
#include "NRF_IRQ.h"
#include "NRF_IRQ_aliases.h"
#include "NRF_IRQ_ISR.h"
#include "SCB_1_SCBCLK.h"
#include "SCB_1_ss1_m.h"
#include "SCB_1_ss1_m_aliases.h"
#include "SCB_1_sclk_m.h"
#include "SCB_1_sclk_m_aliases.h"
#include "SCB_1_miso_m.h"
#include "SCB_1_miso_m_aliases.h"
#include "SCB_1_mosi_m.h"
#include "SCB_1_mosi_m_aliases.h"
#include "SCB_1_ss0_m.h"
#include "SCB_1_ss0_m_aliases.h"
#include "SCB_2_SCBCLK.h"
#include "SCB_2_sda.h"
#include "SCB_2_sda_aliases.h"
#include "SCB_2_scl.h"
#include "SCB_2_scl_aliases.h"
#include "SCB_2_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

